### ISSUE TITLE
index error when convolving new filter

### ISSUE THREAD

**Issue by astrom-tom** [astrofrog/sedfitter#64]
Hello,

I have been trying to use sedfitter with other filters:

Here is the code:
`filt_data = numpy.genfromtxt(filt, dtype = 'float')`  
`w = filt_data[0]`
`r = filt_data[1] `
`f = Filter()`
`f.name = name`
`if wave == 'micron':`
`    f.central_wavelength = effective_w * u.micron`
`    w_m = w * 1e6`
`elif wave == 'ang':`
`    f.central_wavelength = effective_w * u.AA`
`    w_m = w * 1e9`
`f.nu = constants.c*1e3 / w_m  * u.Hz`
`f.response = r`
`###normalize it`
`f.normalize()`
`###and convolve it with the` 
`convolve_model_dir(model_dir, [f])`

When running this code I get the following error:

`INFO: 107184 SEDs found in /run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/YSO_models/models_r06_17jun08/models_r06 [sedfitter.convolve.convolve]
|>-----------------------------------------------------------------|   0 /107k ( 0.00%)INFO: Rebinning filters [sedfitter.convolve.convolve]
|==================================================================| 107k/107k (100.00%)     21m23sTraceback (most recent call last):
  File "makefilters.py", line 65, in <module>
    convolve_model_dir(model_dir, [f])
  File "/home/romain/.local/lib/python2.7/site-packages/sedfitter/convolve/convolve.py", line 41, in convolve_model_dir
    return _convolve_model_dir_1(model_dir, filters, overwrite=overwrite)
  File "/home/romain/.local/lib/python2.7/site-packages/sedfitter/convolve/convolve.py", line 120, in _convolve_model_dir_1
    fluxes[i].sort_to_match(par_table['MODEL_NAME'])
  File "/home/romain/.local/lib/python2.7/site-packages/sedfitter/convolved_fluxes/convolved_fluxes.py", line 171, in sort_to_match
    order = order_to_match(self.model_names, requested_model_names)
  File "/home/romain/.local/lib/python2.7/site-packages/sedfitter/utils/misc.py", line 8, in order_to_match
    return np.argsort(array)[np.argsort(np.argsort(reference))]
IndexError: index 107184 is out of bounds for axis 0 with size 107184
`
Is there anyway to fix it?

**Comment by astrom-tom** [comment]
fixed, bad extraction of the tar file
